# Copyright (c) 2019 Shapelets.io
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

image:
    - Visual Studio 2017
environment:
    GENERATOR: "Visual Studio 15 Win64"
    BOOST_PATH: C:\Libraries\boost_1_69_0
    AF_PATH: C:\Program Files\ArrayFire\v3
    AF_DISABLE_GRAPHICS: 1
    KHIVA_PATH: C:\Program Files\Khiva\v0
    KHIVALIB_DIR: $(KHIVA_PATH)\lib
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
          PATH: $(JAVA_HOME)\bin;$(AF_PATH)\lib;$(KHIVALIB_DIR);$(PATH)
        - JAVA_HOME: C:\Program Files\Java\jdk11
          PATH: $(JAVA_HOME)\bin;$(AF_PATH)\lib;$(KHIVALIB_DIR);$(PATH)
matrix:
    fast_finish: true
cache:
    - C:\tools\vcpkg\installed
    - C:\Program Files\ArrayFire
    - C:\Users\appveyor\.m2
    - C:\ProgramData\chocolatey\bin
    - C:\ProgramData\chocolatey\lib

clone_folder: C:\khiva-java
platform:
    - x64
before_build:
    - ps: if(!(Test-Path -Path "C:\Program Files\ArrayFire" )){ appveyor DownloadFile "http://arrayfire.s3.amazonaws.com/3.6.2/ArrayFire-v3.6.2.exe" }
    - ps: if(!(Test-Path -Path "C:\Program Files\ArrayFire" )){ .\ArrayFire-v3.6.2.exe /S }
    - ps: vcpkg install --triplet x64-windows gtest eigen3
    - ps: if ($env:INSTALL_KHIVA_METHOD -eq "installer"){
            if(!(Test-Path -Path "C:\Program Files\Khiva" )){ appveyor DownloadFile "https://github.com/shapelets/khiva/releases/download/v0.5.0/khiva-v0.5.0-unattended.exe" -FileName khiva-v0.5.0-unattended.exe };
            if(!(Test-Path -Path "C:\Program Files\Khiva" )){ .\khiva-v0.5.0-unattended.exe /S };
          }else{
            git clone --recurse-submodules --depth 1 -q https://github.com/shapelets/khiva.git C:\khiva-library;
            cd C:\khiva-library;
            mkdir build;
            cd build;
            cmake .. -G"$env:GENERATOR" -DArrayFire_DIR="$env:AF_PATH/cmake" -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DBOOST_ROOT="$env:BOOST_PATH" -DKHIVA_USE_CONAN=OFF -DKHIVA_BUILD_DOCUMENTATION=OFF -DKHIVA_BUILD_BENCHMARKS=OFF -DKHIVA_BUILD_EXAMPLES=OFF -DKHIVA_BUILD_TESTS=OFF -DKHIVA_ONLY_CPU_BACKEND=ON;
          }
    - cmake --build . --config Release -- /m
    - cmake --build . --config Release --target INSTALL

    - cd C:\khiva-java
    - start /wait choco install maven
    - pip install codecov
    - java -version
build_script:
    - mvn clean package
on_finish:
    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    - codecov -F Windows -f target/site/jacoco/jacoco.xml
    - ps: |
        $files = Get-ChildItem -Path .\target\surefire-reports -File -Filter *.xml
        foreach ($file in $files) {
            (New-Object System.Net.WebClient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", $file.FullName)
        }
