# Copyright (c) 2019 Shapelets.io
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

image:
    - Visual Studio 2017
environment:
    GENERATOR: "Visual Studio 15 2017 Win64"
    BOOST_PATH: C:\Libraries\boost_1_70_0
    AF_PATH: C:\Program Files\ArrayFire\v3
    AF_DISABLE_GRAPHICS: 1
    KHIVA_PATH: C:\Program Files\Khiva\v0
    KHIVALIB_DIR: $(KHIVA_PATH)\lib
    VCPKG_ROOT: C:\Tools\vcpkg
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
          PATH: $(JAVA_HOME)\bin;$(AF_PATH)\lib;$(KHIVALIB_DIR);$(PATH)
        - JAVA_HOME: C:\Program Files\Java\jdk11
          PATH: $(JAVA_HOME)\bin;$(AF_PATH)\lib;$(KHIVALIB_DIR);$(PATH)
matrix:
    fast_finish: true
cache:
    - C:\tools\vcpkg\installed
    - C:\Program Files\ArrayFire
    - C:\Users\appveyor\.m2
    - C:\ProgramData\chocolatey\bin
    - C:\ProgramData\chocolatey\lib
clone_folder: C:\khiva-java
platform:
    - x64
before_build:
    - ps: |
      env
      if(!(Test-Path -Path "C:\Program Files\ArrayFire" )){ appveyor DownloadFile "http://arrayfire.s3.amazonaws.com/3.6.2/ArrayFire-v3.6.2.exe" }
      if(!(Test-Path -Path "C:\Program Files\ArrayFire" )){ .\ArrayFire-v3.6.2.exe /S }
      vcpkg install --triplet x64-windows gtest eigen3
      git clone -b v0.5.0 --depth 1 --recurse-submodules -q https://github.com/shapelets/khiva.git C:\khiva-library
      cd C:\khiva-library
      mkdir build
      cd build
      cmake .. -G"$env:GENERATOR" -DArrayFire_DIR="$env:AF_PATH/cmake" -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" -DBOOST_ROOT="$env:BOOST_PATH" -DKHIVA_USE_CONAN=OFF -DKHIVA_BUILD_DOCUMENTATION=OFF -DKHIVA_BUILD_BENCHMARKS=OFF -DKHIVA_BUILD_EXAMPLES=OFF -DKHIVA_BUILD_TESTS=OFF;
      cmake --build . --config Release --target install -- /m
      cd C:\khiva-java
      start /wait choco install maven
      pip install codecov
      java -version
build_script:
    - ps: mvn clean package
on_finish:
    # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    - ps: codecov -F Windows -f target/site/jacoco/jacoco.xml
    - ps: |
        $files = Get-ChildItem -Path .\target\surefire-reports -File -Filter *.xml
        foreach ($file in $files) {
            (New-Object System.Net.WebClient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", $file.FullName)
        }
